CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  varchar NOT NULL,
    email varchar NOT NULL UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    description  varchar NOT NULL,
    requestor_id bigint NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar NOT NULL,
    description  varchar NOT NULL,
    available   boolean NOT NULL,
    owner_id    bigint    NOT NULL,
--     request_id  bigint,
    CONSTRAINT pk_items PRIMARY KEY (id),
--     FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE,
    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    start_date timestamp WITHOUT TIME ZONE NOT NULL,
    end_date   timestamp WITHOUT TIME ZONE NOT NULL,
    item_id    bigint                        NOT NULL,
    booker_id  bigint                        NOT NULL,
    status     varchar                     NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS comments
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    text      varchar NOT NULL,
    item_id   bigint   NOT NULL,
    author_id bigint   NOT NULL,
    created timestamp WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);
